<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название группы',
    'Специальность'
);

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;     
} 
?>

<div class="bs-callout bs-callout-warning">    
    Для смены паролей студентам необходимо перейти в <b>группу</b>    
</div>

<table class="table table-hover">
    <thead>
        <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td>
                    <a href="<?=Site::getModurl() . '/' . $v['alias']?>"><?=$v['title']?></a>
                    <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество студентов в группе" class="badge"><?=$v['students_count']?></span>
                </td>
                <td><?=$v['speciality_name']?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>            