<?
use UTest\Kernel\Form;
use UTest\Kernel\Component\Controller;
use UTest\Kernel\Site;
use UTest\Kernel\AppBuilder;

$arTitles = array(
    'ФИО',
    'Логин',
    'Телефон',
    'E-mail'
);

$newDataUser = $data['user'];
$v = $data['form'];

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) { 
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;     
}

if (!empty($newDataUser)) {
    AppBuilder::addBreadcrumb('Генерация новых паролей', Site::getUrl());
    echo Controller::loadComponent('utility', 'pastable', array($newDataUser));
    return;
}
?>

<div class="bs-callout bs-callout-warning">    
    После успешного изменения пароля студенту на данной странице выведутся его данные для входа в систему.<br/>
    Данные будут представлены в табличной форме и содержать: <b>фамилию</b> студента, <b>логин</b> и <b>пароль</b>.<br/>
    Для возврата к списку студентов, воспользуйтесь главным меню или навигационной цепочкой.    
</div>

<table class="table table-bordered">
    <thead>
        <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>
            <td><?=$v['login']?></td>
            <td><?=$v['phone'] ? $v['phone'] : '&mdash;'?></td>
            <td><?=$v['email'] ? $v['email'] : '&mdash;'?></td>
        </tr>
    </tbody>
</table>

<?
if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
}
?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Пароль:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('password', 'password', false , 'form-control password-field', 'password', array('autofocus'=>'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'last_name', $v['last_name'])?>
    <?=Form::input('hidden', 'name', $v['name'])?>
    <?=Form::input('hidden', 'surname', $v['surname'])?>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>