<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;
use UTest\Kernel\Component\Controller;
use UTest\Kernel\AppBuilder;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ФИО' => 'string',
    'Логин' => 'string',
    'Контактный телефон' => 'string',
    'Контактный e-mail' => 'string',
    'Управление'
);

$newDataUsers = $data['users'];
$items = $data['form'];

if (!empty($newDataUsers)) {
    AppBuilder::addBreadcrumb('Генерация новых паролей', Site::getUrl());
    echo Controller::loadComponent('utility', 'pastable', array($newDataUsers));
    return;
}
 
if (count($items) == 0) { 
    echo Form::info('Список пуст');
    return;     
} 

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
} 
?>

<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>
                    <td><?=$v['login']?></td>
                    <td><?=$v['phone'] ? $v['phone'] : '&mdash;'?></td>
                    <td><?=$v['email'] ? $v['email'] : '&mdash;'?></td>
                    <td class="last-column"><?=Form::btnEdit(Site::getUrl().'/editstudent/', $v['id'])?></td>
                </tr>
            <?endforeach?>
        </tbody>
    </table>
    <?=Form::button('Сгенерировать нов. пароли и распечатать', 'btn btn-primary newpass-selected', 'newpass_all', 'Y', 'submit', true)?>
</form>