<?
use UTest\Kernel\Form;

if ($_SESSION['update'] == 'Y') {
    echo Form::success('Данные успешно изменены');
    unset($_SESSION['update']);
}
?>  

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Краткое название учебного заведения:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'univer_name', $data['name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Полное наименование учебного заведения:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'univer_fullname', $data['fullname'] , 'form-control')?>
        </div>
    </div>   
    <div class="form-group">
        <label class="col-lg-2 control-label">Адрес(а):</label>
        <div class="col-lg-10">
            <?=Form::textarea('address', $data['address'], 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Телефон(ы):</label>
        <div class="col-lg-10">
            <?=Form::textarea('phone', $data['phone'], 'form-control')?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button('Применить', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>
