<?
$v = $arResult['request']->_POST ? $arResult['request']->_POST : $arResult['data'];
?>

<?
if ($_SESSION['update'] == 'Y') {
    echo UForm::success('Данные успешно изменены');
    unset($_SESSION['update']);
}
?>  

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Краткое название учебного заведения:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'univer_name', $v['univer_name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Полное наименование учебного заведения:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'univer_fullname', $v['univer_fullname'] , 'form-control')?>            
        </div>
    </div>   
    <div class="form-group">
        <label class="col-lg-2 control-label">Адрес(а):</label>
        <div class="col-lg-10">
            <?=UForm::textarea('address', $v['address'], 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Телефон(ы):</label>
        <div class="col-lg-10">
            <?=UForm::textarea('phone', htmlspecialchars($v['phone']), 'form-control ckeditor')?>            
        </div>
    </div> 
    <div class="form-group">
        <label class="col-lg-2 control-label">Контакты:</label>
        <div class="col-lg-10">
            <?=UForm::textarea('contacts', $v['contacts'], 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Информация:</label>
        <div class="col-lg-10">
            <?=UForm::textarea('info', htmlspecialchars($v['info']), 'form-control ckeditor')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button('Применить', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>
