<?
$v = $arResult['request']->_post ? $arResult['request']->_post : $arResult['data'];
?>

<?if($_SESSION['update'] == 'Y'):?>
    <div class="alert alert-success">Данные успешно изменены</div>
<?
unset($_SESSION['update']);
endif;
?>   

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Краткое название учебного заведения:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'univer_name', $v['univer_name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Полное наименование учебного заведения:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'univer_fullname', $v['univer_fullname'] , 'form-control')?>            
        </div>
    </div>   
    <div class="form-group">
        <label class="col-lg-2 control-label">Адрес:</label>
        <div class="col-lg-10">
            <?=UForm::textarea('address', $v['address'], 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Телефон:</label>
        <div class="col-lg-10">
            <?=UForm::textarea('phone', $v['phone'], 'form-control')?>            
        </div>
    </div> 
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button('Применить', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>
