<?
use UTest\Kernel\Form;

$a = $data['answer_list'];
$r = $data['user_answer'];

$range = range(1, count($a));
$arOptions = array_combine($range, $range);
?>

<ul class="noliststyle test-variant-list">
    <?foreach ($a as $id => $item):?>
        <li>
            <?=Form::select("right[{$id}]", $arOptions , $r[$id])?>
            <label><?=$item['title']?></label>
        </li>
    <?endforeach;?>
</ul>