<?
UAppBuilder::setH('Список тестов');

$arTitles = array(
    'Дата создания',
    'Название теста',
    'Статус',
    'Количество вопросов',
    'Количество пересдач',    
    ''
);

$items = $arResult['data'];
$arStatusTest = Test::getStatusTest();
$arClassOfStatus = array(
    0 => 'label-default',
    1 => 'label-info',
    2 => 'label-success',
);
?>

<?if (empty($items)):?>
    Список пуст
<?else:?>
    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>
                <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                <td><?=$v['title']?></td>
                <td>
                    <span class="label <?=$arClassOfStatus[ $v['status'] ]?>">
                        <?=$arStatusTest[ $v['status'] ]?>
                    </span>
                </td>
                <td><?=$v['count_q']?></td>
                <td><?=$v['retake']?></td>                
                <?if($v['status'] == 0):?>
                    <td class="last-column"><?=UForm::btnTest(USite::getUrl().'/', 'test-'.$v['id'], array('title'=>'Начать тестирование'))?></td>
                <?elseif($v['status'] == 1):?>
                    <td class="last-column"><?=UForm::btnTest(USite::getUrl().'/', 'test-'.$v['id'], array('title'=>'Продолжить тестирование'))?></td>
                <?else:?>
                    <td class="last-column"><?=UForm::btnResult('/student/results/', $v['id'])?></td>
                <?endif;?>
            </tr>
        <?endforeach?>
    </table>    
<?endif?>