<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;
use UTest\Kernel\AppBuilder;

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

$v = $data['question'];
$isLastQuestion = $v['cur_num'] == $data['questions_count'];
?>

<div id="test-errors" class="alert alert-danger" style="display: none"></div>

<? if ($v == false): ?>
    <div id="test-starter">
        <div class="bs-callout bs-callout-warning">
            <p>
                Внимание! После нажатия кнопки <b>начать тест</b> начнётся тестирование.
            </p>
        </div>
        <button type="button" id="test-run" class="btn btn-success">Начать тест</button>
    </div>
<? endif; ?>

<div class="test-wrapper" <?= $v == false ? 'style="display: none"' : '' ?>>
    <header class="test-header">
        <div class="test-q-count">
            Вопрос: <span class="q-count-info"><span id="q-cur-count"><?=$v['cur_num']?></span>&nbsp;/&nbsp;<?=$data['questions_count']?></span>
        </div>
        <div class="test-q-textbox">
            <span class="glyphicon glyphicon-question-sign"></span>
            <div id="test-q-text"><?=html_entity_decode($v['question']['text'])?></div>
        </div>
    </header>
    <div class="test-variantsbox">
        <form id="test-form" class="test-formaction">
            <div id="test-form-variants" class="test-formaction__variants">
                <?= $this->includeTemplate('answer_' . $v['question']['type'], $v) ?>
            </div>
            <div class="test-formaction__control clearfix">
                <button type="button" id="test-end" class="btn btn-danger">Завершить тестирование</button>
                <button type="button" id="test-next" class="btn btn-info" <?=$isLastQuestion ? 'style="display:none"' : ''?>>Дальше</button>
            </div>
            <?=Form::input('hidden', 'url', Site::getModurl())?>
        </form>
    </div>
    <div class="test-q-paginator">
        <ul class="pagination" id="test-pagination">
            <?
            for ($i = 1; $i <= $data['questions_count']; $i++) {
                $classActive = $i == $v['cur_num'] ? 'active' : '';
                $classAnswered = isset($data['used'][$i]) ? 'answered' : '';
            ?>
                <li class="pagination__item pagination__item--<?=$i?> <?=$classActive?>">
                    <a class="pagination__item__link pagination__item__link--<?=$i?> <?=$classAnswered?>" data-num="<?=$i?>" href="#"><?=$i?></a>
                </li>
            <? } ?>
        </ul>
    </div>
</div>

<? AppBuilder::scriptStart(); ?>
<script>
    $(document).ready(function() {
        new TestPassage(<?=$vars['id']?>, '<?=Site::getModurl()?>', <?=json_encode($data['options'])?>);
    });
</script>
<? AppBuilder::scriptEnd(); ?>