<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;
use UTest\Kernel\Test\Passage;

$arTitles = array(
    'Дата создания' => 'string',
    'Название теста' => 'string',
    'Статус' => 'string',
    'Количество вопросов' => 'int',
    '№ пересдачи' => 'int',
    'Управление'
);

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}

$arStatusLabelClasses = [
    Passage::STATUS_WAITED_FOR_START => 'label-default',
    Passage::STATUS_IN_PROCESS => 'label-info',
    Passage::STATUS_FINISHED => 'label-success',
];
?>

<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                <td><?=$v['title']?></td>
                <td>
                    <span class="label <?=$arStatusLabelClasses[intval($v['status'])]?>">
                        <?=Passage::getTestStatuses(intval($v['status']))?>
                    </span>
                </td>
                <td><?=$v['count_q'] // @todo Выводить текущее количество, если было указано 0?></td>
                <td><?=intval($v['retake'])?></td>
                <td class="last-column">
                    <?
                    // @todo Разобраться с ключами
                    switch(intval($v['status'])) {
                        case 0:
                            $btn = Form::btnTest(Site::getUrl() . '/test-' . $v['id'], false, ['title'=>'Начать тестирование']);
                            break;
                            
                        case 1:
                            $btn = Form::btnTest(Site::getUrl() . '/test-' . $v['id'], false, ['title'=>'Продолжить тестирование']);
                            break;
                            
                        case 2:
                            $btn = Form::btnResult('/student/results/', $v['id']);
                            break;
                    }
                    echo $btn;
                    ?>
                </td>
            </tr>
        <?endforeach?>
    </tbody>
</table>