<?
use UTest\Kernel\Form;
use UTest\Kernel\Base;

$arTitles = array(    
    'ФИО' => 'string',
    'Должность' => 'string',
    'Контактный телефон' => 'string',
    'Контактный e-mail' => 'string'
);

$arPositions = Base::getConfig('positions');

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>

<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td><?= $v['last_name'] ?> <?= $v['name'] ?> <?= $v['surname'] ?></td>
                <td><?= $arPositions[$v['post']] ?></td>
                <td><?= $v['phone'] ?: '&mdash;' ?></td>
                <td><?= $v['email'] ?: '&mdash;' ?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>