<?
use UTest\Kernel\Form;
use UTest\Kernel\Base;

$arTitles = array(    
    'ФИО',
    'Должность',    
    'Контактный телефон',
    'Контактный e-mail'
);

$arPositions = Base::getConfig('positions');

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>

<table class="table table-hover">
    <thead>
        <tr>
        <?foreach($arTitles as $title):?>
            <th><?=$title?></th>
        <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td><?= $v['last_name'] ?> <?= $v['name'] ?> <?= $v['surname'] ?></td>
                <td><?= $arPositions[$v['post']] ?></td>
                <td><?= $v['phone'] ?: '&mdash;' ?></td>
                <td><?= $v['email'] ?: '&mdash;' ?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>