<?
$arTitles = array(    
    'ФИО',
    'Должность',    
    'Контактный телефон',
    'Контактный e-mail'
);

$items = $arResult['data']['form'];
$arPost = $this->model->getArPost();
?>

<?if (empty($items)):?>
    Список пуст
<?else:?>    
    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>                
                <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>                
                <td><?=$arPost[ $v['post'] ]?></td>
                <td><?=$v['phone'] ? $v['phone'] : '-'?></td>
                <td><?=$v['email'] ? $v['email'] : '-'?></td>                                    
            </tr>
        <?endforeach?>
    </table>    
<?endif?>