<?
use UTest\Kernel\Form;

$arTitles = array(
    'Название варианта ответа',
    'Верный ответ',
    'Управление'
);

$v = $data['form_question'];
$a = $data['form_answer'];
$r = $data['form_right'];
?>

<?
// запрос на создание нового варианта ответа
if($get['new'] == 'Y') :
    $count = microtime(true); ?>

    <tr>
        <td><?= Form::input('text', "variant[a_{$count}][title]", '', 'form-control answer-text') ?></td>
        <td><label for="a-<?=$count?>"><?=Form::checkbox("right[a_{$count}]", 1, 'answer-checkbox', "a-{$count}")?> отметить</label></td>
        <td class="last-column"><?=Form::btnDelete('#')?></td>
    </tr>

<? else: ?>

    <table class="table table-hover answer-table">
        <thead>
            <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            
            <?
            // Вывод существующих вопросов
            if ($a) {
                foreach($a as $k => $item)
                {
                    static $isFirst = true;
                    if (count($a) > 1 && empty($item['title'])) {
                        continue;
                    }
            ?>
            
                    <tr>
                        <td><?=Form::input('text', "variant[{$k}][title]", $item['title'] , 'form-control answer-text')?></td>
                        <td><label for="a-<?=$k?>"><?=Form::checkbox("right[{$k}]", 1, 'answer-checkbox', "a-{$k}", $r[$k])?> отметить</label></td>
                        <td class="last-column">
                            <?=Form::input('hidden', "variant[{$k}][id]", $item['id'])?>
                            <?=$isFirst ? '' : Form::btnDelete('#', '', array('data-params' => $item['id'] ? "test-{$v['test_id']}/question-{$v['id']}/{$item['id']}" : ''))?>
                        </td>
                    </tr>  
            
            <?
                    $isFirst = false;
                }            
            }  
            // Первый показ формы при создании
            else {
            ?>
            
                <tr>
                    <td><?=Form::input('text', 'variant[a_1][title]', '' , 'form-control answer-text')?></td>
                    <td><label for="a-1"><?=Form::checkbox("right[a_1]", 1, 'answer-checkbox', 'a-1')?> отметить</label></td>
                    <td class="last-column"></td>
                </tr>
                    
            <? } ?>
                       
        </tbody>
    </table>
    <?=Form::button('создать новый вариант ответа', 'btn btn-add-answer')?>

<? endif; ?>
