<?
use UTest\Kernel\Form;

$v = $data['form_question'];
$a = $post['a'] ? $data['form_answer']: reset($data['form_answer']);
$r = $data['form_right'];
?>

<table class="table table-hover answer-table">
    <thead>
        <tr>
            <th>Точное написание верного ответа</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?=Form::input('text', "right", $r, 'form-control answer-text')?></td>
        </tr>    
    </tbody>
</table>
<?=Form::input('hidden', "variant[id]", $a['id'])?>