<?
use UTest\Kernel\Form;

$a = $post['a'] ? $data['form_answer']: reset($data['form_answer']);
?>

<table class="table table-hover answer-table">
    <thead>
        <tr>
            <th>Точное написание верного ответа</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><?=Form::input('text', "answer[right_answer]", $a['right_answer'], 'form-control answer-text')?></td>
        </tr>    
    </tbody>
</table>
<?=Form::input('hidden', "answer[id]", $a['id'])?>