<?
use UTest\Kernel\Form;

$arTitles = array(
    'Название варианта ответа',
    'Укажите верную позицию ответа',
    'Управление'
);

$v = $data['form_question'];
$a = $data['form_answer'];
$r = $data['form_right'];

$arOptions = array();
$allCount = $a ? count($a) : $get['count'] + 1;
for ($i = 1; $i <= $allCount; $i++)
{
    $arOptions[$i] = $i;
}
?>

<?
// запрос на создание нового варианта ответа
if($get['new'] == 'Y') :
    $count = microtime(true); ?>

    <tr>
        <td><?=Form::input('text', "answer[a_{$count}][title]", '', 'form-control answer-text') ?></td>
        <td><?=Form::select("right_answer[a_{$count}]", $arOptions , $needCount, null, 'form-control answer-select-order')?></td>
        <td class="last-column"><?=Form::btnDelete('#')?></td>
    </tr>

<? else: ?>

    <table class="table table-hover answer-table">
        <thead>
            <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            
            <?
            // Вывод существующих вопросов
            if($a) {
                foreach($a as $k => $item)
                {
                    static $isFirst = true;
            ?>
            
                    <tr>
                        <td><?=Form::input('text', "answer[{$k}][title]", $item['title'] , 'form-control answer-text')?></td>
                        <td><?=Form::select("right_answer[{$k}]", $arOptions , $post['a'] ? $r[$k] : $item['right_answer'], null, 'form-control answer-select-order')?></td>
                        <td class="last-column">
                            <?=Form::input('hidden', "answer[{$k}][id]", $item['id'])?>
                            <?=$isFirst ? '' : Form::btnDelete('#', '', array('data-ids' => $item['id'] ? "{$v['test_id']}/{$v['id']}/{$item['id']}" : ''))?>
                        </td>
                    </tr>
            
            <?
                    $isFirst = false;
                }            
            }  
            // Первый показ формы при создании
            else {
            ?>
            
                <tr>
                    <td><?=Form::input('text', 'answer[a_1][title]', '' , 'form-control answer-text')?></td>
                    <td><?=Form::select("right_answer[a_1]", array(1=>1) , 1, null, 'form-control answer-select-order')?></td>
                    <td class="last-column"></td>
                </tr>
                    
            <? } ?>            
                          
        </tbody>
    </table>
    <?=Form::button('создать новый вариант ответа', 'btn btn-add-answer')?>

<? endif; ?>
