<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название группы' => 'string',
    'Специальность' => 'string',
    'Факультет' => 'string'
);

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>

<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td><a href="<?=Site::getUrl() . '/' . $v['alias']?>"><?=$v['title']?></a></td>
                <td><?=$v['speciality_title']?></td>
                <td><?=$v['faculty_title']?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>