<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID' => 'int',
    'Дата создания' => 'string',
    'Название назначенного теста' => 'string',
    'Основа теста' => 'string',
    'Кол-во вопросов' => 'int',
    'Перемешивание' => 'int',
    'Показ верных ответов' => 'int',
    'Управление'
);

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

$items = $data['form'];
?>

<div class="setting-panel">
    <?=Form::btnNew('Назначить тест', Site::getUrl() . '/new')?>
</div>

<?
if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>
    
<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            <?foreach($data as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td class="column-min"><?=$v['id']?></td>
                    <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                    <td><?=$v['title']?></td>
                    <td><?=$v['base_title']?></td>
                    <td><?=$v['count_q']?></td>
                    <td class="column-activity-<?=$v['is_mixing']?>"><?=$v['is_mixing']?></td>
                    <td class="column-activity-<?=$v['is_show_true']?>"><?=$v['is_show_true']?></td>
                    <td class="last-column">
                        <?=Form::btnEdit(Site::getUrl() . '/edit/' . $v['id'])?>
                        <?=Form::btnDelete(Site::getUrl() . '/delete/' . $v['id'])?>
                    </td>
                </tr>
            <?endforeach?>
        </tbody>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
</form>