<?
use UTest\Kernel\Form;

$v = $data['form'];

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
}
?>

<?if(!$vars['id']):?>
    <div class="bs-callout bs-callout-warning">
        <p>
            Будьте внимательны при назначении нового теста.<br/><b>После создания изменить такие параметры как "<i>основа</i>" и "<i>количество вопросов</i>" будет невозможо.</b> Это ограничение связано с целью повысить безопасность и корректность прохождения тестируемыми назначенных тестов.
        </p>
    </div>
<?endif;?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Название назначаемого теста:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>        
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Основа:<?=Form::asterisk()?>
            <?if(!$vars['id']):?>
                <span class="help-block">Необходимо выбрать на основе какого теста будет назначаться создаваемый.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?= $vars['id']
                ? $data['base_list'][$v['test_id']]
                : Form::select('test_id', $data['base_list'] , $v['test_id'], '- Выберите основу теста -', 'form-control')
            ?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Количество вопросов:
            <?if(!$vars['id']):?>
                <span class="help-block">Укажите то количество вопросов, которое будет выведено в тесте.<br/>Указание количества вопросов в "0" будет означать выбор всех вопросов.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?= $vars['id']
                ? (!$v['count_q'] ? 'все': $v['count_q'])
                : Form::input('number', 'count_q', intval($v['count_q']), 'form-control', false, ['min' => 0])?>
        </div>
    </div>
    <!--div class="form-group">
        <label class="col-lg-2 control-label">
            Время на выполнение:
            <?if(!$vars['id']):?>
                <span class="help-block">Указывается в секундах.<br/>Указание времени в "0" будет означать без ограничения.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?= $vars['id']
                ? (!$v['time'] ? 'без ограничений': $v['time'])
                : Form::input('number', 'time', intval($v['time']), 'form-control', false, array('min' => 0))?>
        </div>
    </div-->
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Перемешивание:
            <span class="help-block">При включенной опции вопросы будут выводиться в случайном порядке.</span>
        </label>
        <div class="col-lg-10">
            <?=Form::checkbox("is_mixing", 1, false, false, $v['is_mixing'])?>        
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Показывать верные ответы:            
            <span class="help-block">При включенной опции после окончании тестирования студент сможет просмотреть результат своего теста с полным разбором ошибок: будут отображены верные ответы и отвеченные студентом.</span>
        </label>
        <div class="col-lg-10">
            <?=Form::checkbox("is_show_true", 1, false, false, $v['is_show_true'])?>        
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button($vars['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'id', $v['id'])?>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>