<?
UAppBuilder::setH('Назначенные тесты');

$arTitles = array(
    'Название дисциплины'
);

$items = $arResult['data']['form'];
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 2));?>

<?if (empty($items)):?>
    Ни одной дисциплины не создано
<?else:?>

    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>
                <td><a href="<?=USite::getModurl()?>/for/<?=$this->model->vars['group_code'].'/'.$v['alias']?>"><?=$v['title']?></a> <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Кол-во назначенных тестов" class="badge"><?=$v['test_count']?></span></td>                                
            </tr>
        <?endforeach?>
    </table>
    
<?endif?>