<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название дисциплины' => 'string'
);

if (count($data) == 0) {
    echo Form::info('Ни одной дисциплины не создано');
    return;
}
?>
    
<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td>
                    <a href="<?=Site::getModurl() . '/my/' . $v['alias']?>"><?=$v['title']?></a>
                    <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество тестов" class="badge"><?=$v['test_count']?></span>
                </td>
            </tr>
        <?endforeach?>
    </tbody>
</table>   