<?
UAppBuilder::setH('Тесты по дисциплинам');
$arTitles = array('Название дисциплины');
$items = $arResult['data'];
?>

<?= USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1)); ?>

<? 
if (empty($items)) { 
    echo UForm::info('Ни одной дисциплины не создано');
    return;     
} 
?>
    
<table class="table table-hover">
    <thead>
        <tr>
        <?foreach($arTitles as $title):?>
            <th><?=$title?></th>
        <?endforeach?>
        </tr>
    </thead>
    <?foreach($items as $k => $v):?>
        <tr>
            <td><a href="<?=USite::getModurl()?>/my/<?=$v['alias']?>"><?=$v['title']?></a> <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество тестов" class="badge"><?=$v['test_count']?></span></td>                                
        </tr>
    <?endforeach?>
</table>   