<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;
use UTest\Kernel\Test\Test;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID' => 'int',
    '№' => 'int',
    'Индекс сортировки' => 'int',
    'Вопрос' => 'string',
    'Тип вопроса' => 'string',
    'Управление'
);

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

$items = $data;
?>

<div class="setting-panel">
    <?=Form::btnNew('Создать новый вопрос', Site::getUrl() . '/new/')?>
</div>

<?
if (count($items) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>
    
<div class="bs-callout bs-callout-warning">        
    Создание и редактирование <b>вариантов ответов</b> к вопросам осуществляется внутри формы <b>вопроса</b>        
</div>

<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
        <?
        $count = 1;
        foreach($items as $k => $v):?>
            <tr>
                <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                <td class="column-min"><?=$v['id']?></td>
                <td class="column-disabled column-min" data-sort-value="<?=$count?>">#<?=$count?></td>
                <td><?=$v['ord']?></td>
                <td><?= html_entity_decode($v['text']) ?></td>
                <td><?=Test::getQuestionTypes()[$v['type']]['name']?></td>
                <td class="last-column">
                    <?=Form::btnEdit(Site::getUrl() . '/edit/' . $v['id'])?>
                    <?=Form::btnDelete(Site::getUrl() . '/delete/' . $v['id'])?>
                </td>
            </tr>
        <?
        $count++;
        endforeach;
        ?>
        </tbody>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
</form>