<?
UAppBuilder::setH('Список вопросов');

$arTitles = array(
    UForm::checkbox('check_all', 1, false, 'check-all'),
    '№ вопроса',
    'Вопрос',
    'Тип вопроса',    
    ''
);

$items = $arResult['data'];
$arQType = Test::getTypeQuestion();
$count = 1;
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<div class="setting-panel">
    <?=UForm::btnNew('Создать новый вопрос', USite::getModurl() . '/newmyquestion/in-', $this->model->vars['tid'])?>
</div>

<?if (empty($items)):?>
    Список пуст
<?else:?>
    
    <div class="bs-callout bs-callout-warning">
        <p>
            Создание и редактирование <b>вариантов ответов</b> к вопросам осуществляется внутри формы <b>вопроса</b>
        </p>
    </div>

    <form action="" method="post" class="formaction">
        <table class="table table-hover">
            <thead>
                <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
                </tr>
            </thead>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td><?=UForm::checkbox("i[item_{$v['id']}]", $v['id'], 'check-one')?></td>
                    <td>#<?=$count?></td>
                    <td><?=$v['text']?></td>
                    <td><?=$arQType[ $v['type'] ]['name']?></td>                    
                    <td class="last-column"><?=UForm::btnEdit(USite::getModurl().'/editmyquestion/', 'in-'.$this->model->vars['tid'].'/'.$v['id'])?><?=UForm::btnDelete(USite::getModurl().'/delquestion/', 'test-'.$this->model->vars['tid'].'/'.$v['id'])?></td>
                </tr>
                <?$count++;
            endforeach?>
        </table>
        <?=UForm::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
    </form>
    
<?endif?>