<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование назначенного теста' : 'Назначение нового теста');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data']['form'];

if($arResult['vars']['id'] && empty($v['id']) || empty($arResult)) {
    echo 'тест не найден';
    return;
}
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 2));?>

<?if(!$arResult['vars']['id']):?>
    <div class="bs-callout bs-callout-warning">
        <p>
            Будьте внимательны при назначении нового теста.<br/><b>После создания изменить такие параметры как "<i>основа</i>" и "<i>количество вопросов</i>" будет невозможо.</b> Это ограничение связано с целью повысить безопасность и корректность прохождения тестируемыми назначенных тестов.
        </p>
    </div>
<?endif;?>

<?if (!empty($arResult['errors'])):?>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul class="noliststyle">
        <?foreach ($arResult['errors'] as $k => $e):?>
            <li><?=$e?></li>
        <?endforeach;?>
        </ul>
    </div>
<?endif;?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Название назначаемого теста:
            <span class="help-block">Если данное поле оставить пустым, то название возьмется из теста-основы.</span>
        </label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>        
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Основа:<?=UForm::asterisk()?>
            <?if(!$arResult['vars']['id']):?>
                <span class="help-block">Необходимо выбрать на основе какого теста будет назначаться создаваемый.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?=$arResult['vars']['id'] 
                ? $arResult['data']['test_list'][ $v['test_id'] ] . UForm::input('hidden', 'test_id', $v['test_id'])
                : UForm::select('test_id', $arResult['data']['test_list'] , $v['test_id'], 'Укажите основу теста', 'form-control')
            ?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Количество вопросов:
            <?if(!$arResult['vars']['id']):?>
                <span class="help-block">Укажите то количество вопросов, которое будет выведено в тесте.<br/>Указание количества вопросов в "0" будет означать выбор всех вопросов.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?=$arResult['vars']['id'] ? (!$v['count_q'] ? 'все': $v['count_q']) : UForm::input('number', 'count_q', $v['count_q'] ? $v['count_q'] : 0 , 'form-control', false, array('min' => 0))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Время на выполнение:
            <?if(!$arResult['vars']['id']):?>
                <span class="help-block">Указывается в секундах.<br/>Указание времени в "0" будет означать без ограничения.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?=$arResult['vars']['id'] ? (!$v['count_q'] ? 'все': $v['count_q']) : UForm::input('number', 'time', $v['time'] ? $v['time'] : 0 , 'form-control', false, array('min' => 0))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Перемешивание:
            <span class="help-block">При включенной опции вопросы будут выводиться в случайном порядке.</span>
        </label>
        <div class="col-lg-10">
            <?=UForm::checkbox("is_mixing", 1, false, false, $v['is_mixing'])?>        
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Показывать верные ответы:            
            <span class="help-block">При включенной опции после окончании тестирования студент сможет просмотреть результат своего теста с полным разбором ошибок: будут отображены верные ответы и отвеченные студентом.</span>
        </label>
        <div class="col-lg-10">
            <?=UForm::checkbox("is_show_true", 1, false, false, $v['is_show_true'])?>        
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'id', $v['id'])?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>