<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование теста' : 'Создание нового теста');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data']['form'];
?>

<? 
if ($arResult['vars']['id'] && empty($v['id']) || empty($arResult)) { 
    echo UForm::error('Тест не найден');
    return;     
} 
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<? 
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-lg-2 control-label">Название теста:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>    
    <div class="form-group">
        <label class="col-lg-2 control-label">Для какого предмета:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::select('subject_id', $arResult['data']['subject_list'] , $v['subject_id'], null, 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'id', $v['id'])?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>