<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование вопроса' : 'Создание нового вопроса');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data']['form_question'];
$a = $arResult['data']['form_answer'];
$r = $arResult['data']['form_right'];

if($arResult['vars']['id'] && empty($v['id']) || empty($arResult)) {
    echo 'Вопрос не найден';
    return;
}
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<?if (!empty($arResult['errors'])):?>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul class="noliststyle">
        <?foreach ($arResult['errors'] as $k => $e):?>
            <li><?=$e?></li>
        <?endforeach;?>
        </ul>
    </div>
<?endif;?>

<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-lg-2 control-label">Текст вопроса:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::textarea('question[text]', $v['text'], 'form-control', false, array('autofocus' => 'autofocus'))?>
        </div>
    </div>    
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Тип вопроса:<?=UForm::isRequired()?>
            <?if(!$v['id']):?>
                <span class="help-block">Будьте внимательны при указании типа вопроса. <br/>После создания вопроса изменить тип будет невозможно.</span>
            <?endif;?>
        </label>
        <div class="col-lg-10">
            <?=$v['id'] 
                ?  $arResult['data']['question_type_list'][ $v['type'] ]
                : UForm::select('question[type]', $arResult['data']['question_type_list'] , $v['type'], 'Выберите тип', 'form-control', 'answer-type-select')                    
            ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Варианты ответов:<?=UForm::isRequired()?></label>
        <div class="col-lg-10" id="answer-list">
            <?if(!$v['type']):?>
                Создание вариантов ответов будет доступно после выбора типа вопроса.
            <?else:?>
                
                <?=USiteController::loadComponent('utility', 'answerdisplay', array($v['type'], $v, $a, $r));?>
                
            <?endif;?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'question[id]', $v['id'])?>
    <?=$v['id'] ? UForm::input('hidden', 'question[type]', $v['type']) : ''?>
    <?=UForm::input('hidden', 'url', USite::getModurl())?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>