<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование вопроса' : 'Создание нового вопроса');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data']['form_question'];
$a = $arResult['data']['form_answer'];
$r = $arResult['data']['form_right'];
?>

<? 
if ($arResult['vars']['id'] && empty($v['id'])) { 
    echo UForm::error('Вопрос не найден');
    return;     
} 
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<? 
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-lg-3 control-label">Текст вопроса:<?=UForm::asterisk()?></label>
        <div class="col-lg-9">
            <?=UForm::textarea('question[text]', $v['text'], 'form-control ckeditor', false, array('autofocus' => 'autofocus'))?>
        </div>
    </div>    
    <div class="form-group">
        <label class="col-lg-3 control-label">
            Тип вопроса:<?=UForm::asterisk()?>
            <?if(!$v['id']):?>
                <span class="help-block">Будьте внимательны при указании типа вопроса. <br/>После создания вопроса изменить тип будет невозможно.</span>
            <?endif;?>
        </label>
        <div class="col-lg-9">
            <?=$v['id'] 
                ?  $arResult['data']['question_type_list'][ $v['type'] ]
                : UForm::select('question[type]', $arResult['data']['question_type_list'] , $v['type'], 'Выберите тип', 'form-control', 'answer-type-select')                    
            ?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-3 control-label">
            Индекс сортировки:            
            <span class="help-block">Чем выше значение, тем выше по списку будет располагаться вопрос.</span>            
        </label>
        <div class="col-lg-9">
            <?=UForm::input('text', 'question[ord]', $arResult['data']['ord'], 'form-control')?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-3 control-label">Варианты ответов:<?=UForm::asterisk()?></label>
        <div class="col-lg-9" id="answer-list">
            <?if(!$v['type']):?>
                Создание вариантов ответов будет доступно после выбора типа вопроса.
            <?else:?>                
                <?=USiteController::loadComponent('prepod.tests', 'answerdisplay', array($v['type'], $v, $a, $r), array('setTitle' => null, 'addBreadcrumb' => false));?>                
            <?endif;?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-3 col-lg-9">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'question[id]', $v['id'])?>
    <?=$v['id'] ? UForm::input('hidden', 'question[type]', $v['type']) : ''?>
    <?=UForm::input('hidden', 'url', USite::getModurl())?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>