<?
$v = $arResult['data'];
?>

<?if($_SESSION['update'] == 'Y'):?>
    <div class="alert alert-success">Данные успешно изменены</div>
<?
unset($_SESSION['update']);
endif;
?>    

<form class="form-horizontal" method="post" action="">    
    <div class="form-group">
        <label class="col-lg-2 control-label">Контактный телефон:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'phone', $v['phone'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">E-mail для связи:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'email', $v['email'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>
