<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID' => 'int',
    'Название группы' => 'string',
    'Специальность' => 'string',
    'Управление'
);

$items = $data;
?>

<div class="setting-panel">
    <?=Form::btnNew('Создать новую группу', Site::getModurl() . '/newgroup')?>    
</div>

<? 
if (count($items) == 0) {
    echo Form::info('Список пуст');
    return;     
} 
?>

<div class="bs-callout bs-callout-warning">    
    Для создания новых <b>студентов</b> необходимо перейти в <b>группу</b>    
</div>

<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td class="column-min"><?=$v['id']?></td>
                    <td>
                        <a href="<?=Site::getModurl() . '/' . $v['alias']?>"><?=$v['title']?></a>
                        <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество студентов в группе" class="badge"><?=$v['students_count']?></span>
                    </td>
                    <td><?=$v['speciality_name']?></td>
                    <td class="last-column">
                        <?=Form::btnEdit(Site::getModurl().'/editgroup/', $v['id'])?>
                        <?=Form::btnDelete(Site::getModurl().'/delete/', 'group/'.$v['id'])?>
                    </td>
                </tr>
            <?endforeach?>
        </tbody>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>    
</form>