<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование группы' : 'Создание новой группы');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data']['form'];
?>

<? 
if ($arResult['errors'] == ERROR_ELEMENT_NOT_FOUND) {
    echo UForm::error('Группа не найдена');
    return; 
} 
?>

<? 
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Наименование группы:<?=UForm::asterisk()?></label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>    
    <div class="form-group">
        <label class="col-lg-2 control-label">К какой специальности относится:<?=UForm::asterisk()?></label>
        <div class="col-lg-10">
            <?=UForm::select('speciality_id', $arResult['data']['speciality_list'] , $v['speciality_id'], null, 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'id', $v['id'])?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>