<?
use UTest\Kernel\Form;
use UTest\Kernel\Component\Controller;
use UTest\Kernel\AppBuilder;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'ФИО',
    'Логин',
    'Контактный телефон',
    'Контактный e-mail',
    'Управление'
);

$newDataUsers = $data['users'];
$items = $data['form'];

if (!empty($newDataUsers)) {
    AppBuilder::addBreadcrumb('Генерация новых паролей', Site::getUrl());
    echo Controller::loadComponent('utility', 'pastable', array($newDataUsers));
    return;
}

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return; 
}
?>

<div class="setting-panel">    
    <?=Form::btnNew('Создать нового студента', Site::getUrl() . '/newstudent')?>
</div>
    
<?
if (count($items) == 0) {
    echo Form::info('Список пуст');
    return;     
} 

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
} 
?>

<form action="" method="post" class="formaction">
    <table class="table table-hover">
        <thead>
            <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[item_{$v['id']}]", $v['id'], 'check-one')?></td>
                    <td><?=$v['id']?></td>
                    <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>
                    <td><?=$v['login']?></td>
                    <td><?=$v['phone'] ?: '&mdash;'?></td>
                    <td><?=$v['email'] ?: '&mdash;'?></td>
                    <td class="last-column">
                        <?=Form::btnEdit(Site::getUrl().'/editstudent/', $v['id'])?>
                        <?=Form::btnDelete(Site::getModurl().'/delete/', 'student/'.$v['id'])?>
                    </td>
                </tr>
            <?endforeach?>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
    <?=Form::button('Сгенерировать нов. пароли и распечатать', 'btn btn-primary newpass-selected', 'newpass_all', 'Y', 'submit', true)?>
</form>