<?
UAppBuilder::setH('Cтуденты');

$arTitles = array(
    UForm::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'ФИО',
    'Логин',
    'Контактный телефон',
    'Контактный e-mail',
    'Управление'
);

$newDataUsers = $arResult['data']['users'];
$items = $arResult['data']['form'];
?>

<?
if (!empty($newDataUsers)) {
    UAppBuilder::addBreadcrumb('Генерация новых паролей', USite::getUrl());
    echo USiteController::loadComponent('utility', 'pastable', array($newDataUsers));
    return;
}
?>

<? 
if ($arResult['errors'] == ERROR_ELEMENT_NOT_FOUND) {
    echo UForm::error('Группа не найдена');
    return; 
} 
?>

<div class="setting-panel">    
    <?=UForm::btnNew('Создать нового студента', USite::getUrl() . '/newstudent')?>
</div>
    
<? 
if (empty($items)) { 
    echo UForm::info('Список пуст');
    return;     
} 
?>
    
<? 
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<form action="" method="post" class="formaction">
    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>
                <td class="checkbox-column"><?=UForm::checkbox("i[item_{$v['id']}]", $v['id'], 'check-one')?></td>
                <td><?=$v['id']?></td>
                <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>
                <td><?=$v['login']?></td>
                <td><?=$v['phone'] ?: '&mdash;'?></td>
                <td><?=$v['email'] ?: '&mdash;'?></td>
                <td class="last-column">
                    <?=UForm::btnEdit(USite::getUrl().'/editstudent/', $v['id'])?>
                    <?=UForm::btnDelete(USite::getModurl().'/delete/', 'student/'.$v['id'])?>
                </td>
            </tr>
        <?endforeach?>
    </table>
    <?=UForm::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
    <?=UForm::button('Сгенерировать нов. пароли и распечатать', 'btn btn-primary newpass-selected', 'newpass_all', 'Y', 'submit', true)?>
</form>