<?
use UTest\Kernel\Form;
use UTest\Kernel\Utilities;

$arTitles = array(
    'Дата выкладывания',
    'Тип',
    'Название документа',
    'Размер',
    'Формат',
    'Скачать',
);

if (count($data) == 0) {
    echo Form::info('Дисциплины с доступным материалом отсутствуют');
    return;
}
?>

<table class="table table-hover">
    <thead>
        <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):
            $isComment = !empty($v['comment']);
        ?>
            <tr>
                <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                <td><?= $isComment ? 'комментарий' : 'файл' ?></td>
                <?if ($isComment):?>
                    <td colspan="4">
                        <blockquote class="comment-block"><?=html_entity_decode($v['comment'])?></blockquote>
                    </td>
                <?else:?>
                    <td><?=$v['filename']?></td>
                    <td><?=Utilities::bytesToSize($v['size'])?></td>
                    <td><?=$v['extension']?></td>
                    <td class="column-min">[<a href="?download=<?=$v['material_id']?>">скачать</a>]</td>
                <?endif;?>
            </tr>
        <?endforeach?>
    </tbody>
</table>