<?
use UTest\Kernel\Form;
use UTest\Kernel\Utilities;

$arTitles = array(
    'Дата выкладывания' => 'string',
    'Тип' => 'string',
    'Название документа' => 'string',
    'Размер',
    'Формат',
    'Скачать',
);

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

if (count($data) == 0) {
    echo Form::info('Дисциплины с доступным материалом отсутствуют');
    return;
}
?>

<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):
            $isComment = !empty($v['comment']);
        ?>
            <tr>
                <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                <td><?= $isComment ? 'комментарий' : 'файл' ?></td>
                <?if ($isComment):?>
                    <td colspan="4">
                        <blockquote class="comment-block"><?=html_entity_decode($v['comment'])?></blockquote>
                    </td>
                <?else:?>
                    <td><?=$v['filename']?></td>
                    <td><?=Utilities::bytesToSize($v['size'])?></td>
                    <td><?=$v['extension']?></td>
                    <td class="column-min">[<a href="?download=<?=$v['material_id']?>">скачать</a>]</td>
                <?endif;?>
            </tr>
        <?endforeach?>
    </tbody>
</table>