<?
UAppBuilder::setH('Дисциплины с доступным материалом');

$arTitles = array(
    'Название дисциплины',
    'Преподаватель'
);

$items = $arResult['data'];
?>

<?if (empty($items)):?>
    Дисциплины с доступным материалом отсутствуют
<?else:?>
    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>                
                <td><a href="<?=USite::getModurl()?>/my/<?=$v['alias']?>"><?=$v['title']?></a> <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество информации" class="badge"><?=$v['material_count']?></span></td>                                
                <td><?=$v['prepod_last_name'].' '.$v['prepod_name'].' '.$v['prepod_surname']?></td>
            </tr>
        <?endforeach?>
    </table>
<?endif;?>