<?
UAppBuilder::setH('Список выложенной информации');

$arTitles = array(
    'Дата выкладывания',
    'Название документа',
    'Размер',
    'Формат',
    'Скачать',
);

$items = $arResult['data'];
?>


<?if (empty($items)):?>
    Информации не найдено
<?else:?>    
    <table class="table table-hover">
        <thead>
            <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
            </tr>
        </thead>
        <?foreach($items as $k => $v):?>
            <tr>
                <td><?=date("d.m.Y",strtotime($v['date']))?></td>                
                <?if ($v['material_id'] === null):?>
                    <td colspan="4">
                        <blockquote class="comment-block"><?=nl2br($v['comment'])?></blockquote>
                    </td>
                <?else:?>
                    <td><?=$v['filename']?></td>
                    <td><?=UAppBuilder::bytesToSize($v['size'])?></td>
                    <td><?=$v['extension']?></td>
                    <td><a href="?download=<?=$v['material_id']?>">скачать</a></td>                
                <?endif;?>
            </tr>
        <?endforeach?>
    </table>
<?endif?>