<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название дисциплины' => 'string',
    'Преподаватель' => 'string'
);

if (count($data) == 0) {
    echo Form::info('Дисциплины с доступным материалом отсутствуют');
    return;
}
?>

<table class="table table-hover table-sort">
    <thead>
        <tr>
            <?foreach($arTitles as $k => $v):
                $title = is_string($k) ? $k : $v;
                $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
            ?>
                <th <?=$dataSort?>><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td>
                    <a href="<?=Site::getUrl() . '/' . $v['subject_code'] ?>"><?=$v['subject_name']?></a>
                    <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество материала" class="badge"><?=$v['material_count']?></span>
                </td>
                <td><?=$v['prepod_last_name'].' '.$v['prepod_name'].' '.$v['prepod_surname']?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>