<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название группы',
    'Специальность',
    'Факультет'
);

if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;
}
?>

<table class="table table-hover">
    <thead>
        <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td><a href="<?=Site::getUrl() . '/' . $v['alias']?>"><?=$v['title']?></a></td>
                <td><?=$v['speciality_title']?></td>
                <td><?=$v['faculty_title']?></td>
            </tr>
        <?endforeach?>
    </tbody>
</table>