<?
UAppBuilder::setH('Материал для групп');

$arTitles = array(
    'Название группы'
);

$items = $arResult['data']['form'];
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 2));?>

<table class="table table-hover">
    <thead>
        <tr>
        <?foreach($arTitles as $title):?>
            <th><?=$title?></th>
        <?endforeach?>
        </tr>
    </thead>
    <?foreach($items as $k => $v):?>
        <tr>
            <td><a href="<?=USite::getModurl()?>/for/<?=$v['alias']?>"><?=$v['title']?></a></td>                                
        </tr>
    <?endforeach?>
</table>