<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
}
?>

<form class="form-horizontal" method="post" action="" enctype="multipart/form-data">
    <div class="form-group">
        <label class="col-lg-2 control-label">
            Укажите какие файлы будут доступны для выбранной группы по данному предмету:
            <span class="help-block">Для выбора нескольких файлов используйте [ctrl]+[ЛКМ]</span>
        </label>
        <div class="col-lg-10">
            <?=Form::select('materials[]', $data['doc_list'] , $data['active_list'], false, 'form-control', false, true, 7)?>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button('Применить', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>