<?
UAppBuilder::setH('Материал для дисциплин');

$arTitles = array(
    'Название дисциплины'
);

$items = $arResult['data'];
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<table class="table table-hover">
    <thead>
        <tr>
        <?foreach($arTitles as $title):?>
            <th><?=$title?></th>
        <?endforeach?>
        </tr>
    </thead>
    <?foreach($items as $k => $v):?>
        <tr>
            <td><a href="<?=USite::getModurl()?>/my/<?=$v['alias']?>"><?=$v['title']?></a> <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество файлов" class="badge"><?=$v['material_count']?></span></td>                                
        </tr>
    <?endforeach?>
</table>
