<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    'Название дисциплины'
);

if (count($data) == 0) {
    echo Form::info('Ни одной дисциплины не создано');
    return;
}
?>

<table class="table table-hover">
    <thead>
        <tr>
            <?foreach($arTitles as $title):?>
                <th><?=$title?></th>
            <?endforeach?>
        </tr>
    </thead>
    <tbody>
        <?foreach($data as $k => $v):?>
            <tr>
                <td>
                    <a href="<?=Site::getModurl() . '/my/' . $v['alias']?>"><?=$v['title']?></a>
                    <span rel="tooltip" data-placement="right" data-toggle="tooltip" title="Количество файлов" class="badge"><?=$v['material_count']?></span>
                </td>
            </tr>
        <?endforeach?>
    </tbody>
</table>
