<?
UAppBuilder::setH('Список документов');

$arTitles = array(
    UForm::checkbox('check_all', 1, false, 'check-all'),
    'Дата загрузки',
    'Название документа',
    'Размер',
    'Формат',
    'Скачать',
    'Управление'
);

$items = $arResult['data'];
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 1));?>

<div class="setting-panel">
    <?=UForm::btnNew('Загрузить новый материал', USite::getModurl() . '/newmy/', $this->model->vars['subject_code'])?>
</div>

<?if (empty($items)):?>
    Список пуст
<?else:?>

    <form action="" method="post" class="formaction">
        <table class="table table-hover">
            <thead>
                <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
                </tr>
            </thead>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=UForm::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td><?=date("d.m.Y",strtotime($v['date']))?></td>
                    <td><?=$v['filename']?></td>
                    <td><?=UAppBuilder::bytesToSize($v['size'])?></td>
                    <td><?=$v['extension']?></td>
                    <td><a href="?download=<?=$v['id']?>">скачать</a></td>
                    <td class="last-column"><?=UForm::btnEdit(USite::getModurl().'/editmy/', $v['id'])?><?=UForm::btnDelete(USite::getModurl().'/delete/', 'my/'.$v['id'])?></td>
                </tr>
            <?endforeach?>
        </table>
        <?=UForm::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
    </form>
    
<?endif?>