<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование комментария' : 'Создание нового комментария');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data'];

if($arResult['vars']['id'] && empty($v['id']) || empty($arResult)) {
    echo 'Комментарий не найден';
    return;
}
?>

<?=USiteController::loadComponent('utility', 'tabs', array($this->arTabs, 2));?>

<?if (!empty($arResult['errors'])):?>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul class="noliststyle">
        <?foreach ($arResult['errors'] as $k => $e):?>
            <li><?=$e?></li>
        <?endforeach;?>
        </ul>
    </div>
<?endif;?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Комментарий:<?=UForm::asterisk()?></label>
        <div class="col-lg-10">
            <?=UForm::textarea('comment', $v['comment'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>        
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'id', $v['id'])?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>