<form class="main-form" action="" method="post">
    
    <? 
    if (!empty($arResult['errors'])) {
        echo UForm::error($arResult['errors'], true);
    } 
    ?>
    
    <div class="form-group">
        <?=UForm::input('text', 'login', $arResult['request']->_POST['login'], 'form-control', false, array('placeholder'=>'Ваш логин', 'autocomplete'=>'off'))?>        
    </div>    
    <div class="form-group">
        <?=UForm::input('password', 'pass', false, 'form-control', false, array('placeholder'=>'Ваш пароль'))?>        
    </div>    
    <div>
        <?=UForm::button('Войти', 'btn btn-warning')?>
    </div>  
    <?=UForm::input('hidden', 'a', 'Y')?>        
</form>