<?
use UTest\Kernel\Form;
?>

<form class="main-form" action="" method="post">
    
    <?
    if ($this->hasErrors()) {
        echo Form::error($this->getErrors(), true);
    } 
    ?>
    
    <div class="form-group">
        <?=Form::input('text', 'login', $post['login'], 'form-control', false, ['placeholder'=>'Ваш логин', 'autocomplete'=>'off'])?>
    </div>    
    <div class="form-group">
        <?=Form::input('password', 'pass', false, 'form-control', false, ['placeholder'=>'Ваш пароль'])?>
    </div>    
    <div>
        <?=Form::button('Войти', 'btn btn-warning')?>
    </div>  
    <?=Form::input('hidden', 'a', 'Y')?>
</form>