<?
$a = $arResult['data']['answer'];
$r = $arResult['data']['right'];

$arOptions = array();
for ($i = 1; $i <= count($a); $i++)
{
    $arOptions[$i] = $i;
}
?>

<ul class="noliststyle test-variant-list">
    <?foreach ($a as $k => $title):?>
    <li>
        <?=UForm::select("right_answer[{$k}]", $arOptions, (array)$r[$k])?>
        <label><?=$title?></label>
    </li>
    <?endforeach;?>
</ul>