<? 
use UTest\Kernel\Form;

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
} 

if ($_SESSION['update'] == 'Y') {
    echo Form::success('Пароль успешно изменён');
    unset($_SESSION['update']);
}
?>    

<form class="form-horizontal" method="post" action="">    
    <div class="form-group">
        <label class="col-lg-2 control-label">Новый пароль:</label>
        <div class="col-lg-10">
            <?=Form::input('password', 'password', false , 'form-control password-field', 'password')?>        
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>