<?if (!empty($arResult['errors'])):?>
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul class="noliststyle">
        <?foreach ($arResult['errors'] as $k => $e):?>
            <li><?=$e?></li>
        <?endforeach;?>
        </ul>
    </div>
<?endif;?>

<?if($_SESSION['update'] == 'Y'):?>
    <div class="alert alert-success">Пароль успешно изменён</div>
<?
unset($_SESSION['update']);
endif;
?>    

<form class="form-horizontal" method="post" action="">    
    <div class="form-group">
        <label class="col-lg-2 control-label">Новый пароль:</label>
        <div class="col-lg-10">
            <?=UForm::input('password', 'password', false , 'form-control password-field', 'password')?>        
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>
