<p>Вы зашли в систему как <b>«Студент»</b>.</p>
<p>Слева расположено доступное меню разделов, включающее следующие пункты:</p>
<ul>
    <li><a href="#test">Тесты</a></li>
    <li><a href="#result">Мои результаты</a></li>
    <li><a href="#material">Материал</a></li>
    <li><a href="#prepod">Преподаватели</a></li>
</ul>

<section class="help-section">
    <a name="test"></a>
    <h2>Тесты</h2>
    <div class="bs-callout bs-callout-info">
        <p>В данном разделе содержится <b>список назначенных тестов</b> для прохождения.</p>
        <p>
            Чтобы перейти к тестированию, нужно выбрать дисциплину, по которой был назначен тест, 
            и из списка предлагаемых тестов выбрать необходимый.<br/> 
            Для начала/продолжения тестирования нужно воспользоваться служебными 
            кнопками справа от интересующего теста.
        </p>        
        <figure>
            <img src="<?=CURRENT_THEME_URL?>/img/sys/_student/s-1.png" />
            <figcaption>Список дисциплин</figcaption>
        </figure>
        <figure>
            <img src="<?=CURRENT_THEME_URL?>/img/sys/_student/s-2.png" />
            <figcaption>Список назначенных тестов</figcaption>
        </figure>
    </div>
</section>

<section class="help-section">
    <a name="result"></a>
    <h2>Мои результаты</h2>
    <div class="bs-callout bs-callout-info">
        <p>В данном разделе можно просматривать <b>результаты тестирования</b> по пройденным тестам.</p>
        <p>
            Для просмотра отчета о результате тестирования, нужно воспользоваться служебной кнопкой, что
            располагается в правой части строки интересующего теста.
        </p>        
        <figure>
            <img src="<?=CURRENT_THEME_URL?>/img/sys/_student/s-3.png" />
            <figcaption>Список завершенных тестов</figcaption>
        </figure>        
    </div>
</section>

<section class="help-section">
    <a name="material"></a>
    <h2>Материал</h2>
    <div class="bs-callout bs-callout-info">
        <p>В данном разделе можно ознакомиться с <b>информационными единицами</b>, которую выложили преподаватели для вашей группы.</p>
        <p><i>Информационная единица</i> &ndash; это объект информации, представленный в виде файла или текстового комментария от преподавателя.<p/>
        <p>Чтобы перейти к доступным материалам, необходимо выбрать дисциплину. Затем покажется список всей доступной информации по выбранной дисциплине.</p>        
        <figure>
            <img src="<?=CURRENT_THEME_URL?>/img/sys/_student/s-4.png" />
            <figcaption>Список дисциплин с доступной информацией</figcaption>
        </figure>        
    </div>
</section>

<section class="help-section">
    <a name="prepod"></a>
    <h2>Преподаватели</h2>
    <div class="bs-callout bs-callout-info">
        <p>В данном разделе можно узнать <b>информацию о преподавателях</b>.</p>      
        <p>
            Раздел содержит список всех преподавателей, зарегистрированных в системе.
            По каждому преподавателю можно просмотреть его полные ФИО, занимаемую должность, а также контактные данные.
        </p>
    </div>
</section>

<section class="help-section">
    <h2>Графические элементы управления</h2>
    <div class="bs-callout bs-callout-warning">
        <table class="help-table">
            <tr>
                <td>
                    <img src="<?=CURRENT_THEME_URL?>/img/sys/btn-run.gif" />
                </td>
                <td>&ndash;</td>
                <td>начать/продолжить тестирование</td>
            </tr>
            <tr>
                <td>
                    <img src="<?=CURRENT_THEME_URL?>/img/sys/btn-result.gif" />
                </td>
                <td>&ndash;</td>
                <td>просмотреть результаты тестирования</td>
            </tr>            
        </table>
    </div>
</section>

<section class="help-section">
    <h2>Навигация по системе</h2>
    <div class="bs-callout bs-callout-warning">
        <p>
            Для перехода из раздела в раздел используйте меню резделов слева.<br/>
            Для навигации внутри выбранного раздела можно использовать навигационную цепочку («хлебные крошки»).
        </p>
    </div>
</section>