<?
use UTest\Kernel\Form;
use UTest\Kernel\Component\Controller;
use UTest\Kernel\AppBuilder;
use UTest\Kernel\Site;

$newDataUser = $data['user'];
$v = $data['form'];
$arPosts = $data['posts'];

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return; 
} 

if (!empty($newDataUser)) {
    AppBuilder::addBreadcrumb('Новый пользователь', Site::getUrl());
    echo Controller::loadComponent('utility', 'pastable', array($newDataUser));
    return;     
}
?>

<? if ($vars['id']): ?>
    <div class="bs-callout bs-callout-warning">
        При задании <b>нового пароля</b> преподавателю на данной странице выведутся его данные для входа в систему.
    </div>
<? else: ?>
    <div class="bs-callout bs-callout-warning">
        После успешного создания нового преподавателя на данной странице выведутся его данные для входа в систему.<br/>
        Данные будут представлены в табличной форме и содержать: <b>фамилию</b> преподавателя, <b>логин</b> и <b>пароль</b>.<br/>
        Для возврата к списку преподавателей, воспользуйтесь главным меню или навигационной цепочкой.
    </div>
<? endif; ?>

<? 
if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
} 
?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Фамилия:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'last_name', $v['last_name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Имя:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'name', $v['name'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Отчество:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'surname', $v['surname'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Должность:</label>
        <div class="col-lg-10">
            <?=Form::select('post', $arPosts, $v['post'], false, 'form-control')?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Контактный телефон:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'phone', $v['phone'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Контактный e-mail:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'email', $v['email'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label"><?=$vars['id'] ? 'Новый пароль:' : 'Пароль:'.Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('password', 'password', false , 'form-control password-field', 'password')?>            
        </div>
    </div>    
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button($vars['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'id', $v['id'])?>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>