<?

use UTest\Kernel\Form;
use UTest\Kernel\AppBuilder;
use UTest\Kernel\Component\Controller;
use UTest\Kernel\Site;
use UTest\Kernel\Base;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'ФИО',
    'Логин',
    'Должность',
    'Телефон',
    'E-mail',
    'Управление'
);

$newDataUsers = $data['users'];
$items = $data['form'];
$arPositions = Base::getConfig('positions');

if (!empty($newDataUsers)) {
    AppBuilder::addBreadcrumb('Генерация новых паролей', Site::getUrl());
    echo Controller::loadComponent('utility', 'pastable', array($newDataUsers));
    return;
}
?>

<div class="setting-panel">
    <?= Form::btnNew('Создать нового преподавателя', Site::getModurl() . '/newprepod') ?>
</div>

<?
if (empty($items)) {
    echo Form::info('Список пуст');
    return;
}

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
}
?>

<form action="" method="post" class="formaction">
    <table class="table table-hover">
        <thead>
        <tr>
            <? foreach ($arTitles as $title): ?>
                <th><?= $title ?></th>
            <? endforeach ?>
        </tr>
        </thead>
        <tbody>
            <? foreach ($items as $k => $v): ?>
                <tr>
                    <td class="checkbox-column"><?= Form::checkbox("i[]", $v['id'], 'check-one') ?></td>
                    <td><?= $v['id'] ?></td>
                    <td><?= $v['last_name'] ?> <?= $v['name'] ?> <?= $v['surname'] ?></td>
                    <td><?= $v['login'] ?></td>
                    <td><?= $arPositions[$v['post']] ?></td>
                    <td><?= $v['phone'] ?: '&mdash;' ?></td>
                    <td><?= $v['email'] ?: '&mdash;' ?></td>
                    <td class="last-column">
                        <?= Form::btnEdit(Site::getModurl() . '/edit/', $v['id']) ?>
                        <?= Form::btnDelete(Site::getModurl() . '/delete/', $v['id']) ?>
                    </td>
                </tr>
            <? endforeach ?>
        </tbody>
    </table>
    <?= Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true) ?>
    <?= Form::button('Сгенерировать нов. пароли и распечатать', 'btn btn-primary newpass-selected', 'newpass_all', 'Y','submit', true) ?>
</form>