<?
$arTitles = array(
    UForm::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'ФИО',
    'Логин',
    'Должность',    
    'Контактный телефон',
    'Контактный e-mail',
    ''
);

$newDataUsers = $arResult['data']['users'];
$items = $arResult['data']['form'];
$arPost = $this->model->getArPost();
?>

<?
if (is_array($newDataUsers)) {
    UAppBuilder::addBreadcrumb('Генерация новых паролей', USite::getUrl());
    echo USiteController::loadComponent('utility', 'pastable', array($newDataUsers));
    return;
}
?>

<div class="setting-panel">    
    <?=UForm::btnNew('Создать нового преподавателя', USite::getModurl() . '/newprepod')?>
</div>

<?if (empty($items)):?>
    Список пуст
<?else:?>
    
    <?if (!empty($arResult['errors'])):?>
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul class="noliststyle">
            <?foreach ($arResult['errors'] as $k => $e):?>
                <li><?=$e?></li>
            <?endforeach;?>
            </ul>
        </div>
    <?endif;?>
    
    <form action="" method="post" class="formaction">
        <table class="table table-hover">
            <thead>
                <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
                </tr>
            </thead>
            <?foreach($items as $k => $v):?>
                <tr>
                    <td><?=UForm::checkbox("i[item_{$v['id']}]", $v['id'], 'check-one')?></td>
                    <td><?=$v['id']?></td>
                    <td><?=$v['last_name']?> <?=$v['name']?> <?=$v['surname']?></td>
                    <td><?=$v['login']?></td>
                    <td><?=$arPost[ $v['post'] ]?></td>
                    <td><?=$v['phone'] ? $v['phone'] : '-'?></td>
                    <td><?=$v['email'] ? $v['email'] : '-'?></td>                    
                    <td class="last-column"><?=UForm::btnEdit(USite::getModurl().'/edit/', $v['id'])?><?=UForm::btnDelete(USite::getModurl().'/delete/', $v['id'])?></td>
                </tr>
            <?endforeach?>
        </table>
        <?=UForm::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
        <?=UForm::button('Сгенерировать нов. пароли и распечатать', 'btn btn-primary newpass-selected', 'newpass_all', 'Y', 'submit', true)?>
    </form>
<?endif?>