<?
use UTest\Kernel\Form;
use UTest\Kernel\Base;

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
} 

if ($_SESSION['update'] == 'Y') {
    echo Form::success('Данные успешно обновлены');
    unset($_SESSION['update']);
}

$v = $data;
?>    

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Фамилия:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'last_name', $v['last_name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Имя:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'name', $v['name'] , 'form-control')?>            
        </div>
    </div>   
    <div class="form-group">
        <label class="col-lg-2 control-label">Отчество:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'surname', $v['surname'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Должность:</label>
        <div class="col-lg-10">
            <?=Form::select('post', Base::getConfig('positions') , $v['post'], false, 'form-control')?>
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Контактный телефон:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'phone', $v['phone'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">E-mail для связи:</label>
        <div class="col-lg-10">
            <?=Form::input('text', 'email', $v['email'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>
