<?
$v = $arResult['data'];
?>

<? 
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<?
if ($_SESSION['update'] == 'Y') {
    echo UForm::success('Пароль успешно изменён');
    unset($_SESSION['update']);
}
?>    

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Фамилия:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'last_name', $v['last_name'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Имя:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'name', $v['name'] , 'form-control')?>            
        </div>
    </div>   
    <div class="form-group">
        <label class="col-lg-2 control-label">Отчество:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'surname', $v['surname'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Должность:</label>
        <div class="col-lg-10">
            <?//=UForm::input('text', 'post', $v['post'] , 'form-control')?>            
            <?=UForm::select('post', $this->model->getArPost() , $v['post'], null, 'form-control')?>  
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Контактный телефон:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'phone', $v['phone'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">E-mail для связи:</label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'email', $v['email'] , 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button('Изменить', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>
