<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'Название факультета',
    'Управление'
);
?>

<div class="setting-panel">
    <?=Form::btnNew('Создать новый факультет', Site::getModurl() . '/newfaculty')?>    
</div>

<? 
if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;     
} 
?>

<div class="bs-callout bs-callout-warning">
    Для создания новых <b>специальностей</b> необходимо перейти в раздел <b>факультета</b>    
</div>

<form action="" method="post" class="formaction">
    <table class="table table-hover">
        <thead>
            <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <?foreach($data as $k => $v):?>
            <tr>
                <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                <td><?=$v['id']?></td>
                <td><a href="<?=Site::getModurl()?>/<?=$v['alias']?>"><?=$v['title']?></a></td>
                <td class="last-column">
                    <?=Form::btnEdit(Site::getModurl().'/editfaculty/', $v['id'])?>
                    <?=Form::btnDelete(Site::getModurl().'/delete/', 'faculty/'.$v['id'])?>
                </td>
            </tr>
        <?endforeach?>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
</form>