<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID' => 'int',
    'Название факультета' => 'string',
    'Управление'
);
?>

<div class="setting-panel">
    <?=Form::btnNew('Создать новый факультет', Site::getModurl() . '/newfaculty')?>    
</div>

<? 
if (count($data) == 0) {
    echo Form::info('Список пуст');
    return;     
} 
?>

<div class="bs-callout bs-callout-warning">
    Для создания новых <b>специальностей</b> необходимо перейти в раздел <b>факультета</b>    
</div>

<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            <?foreach($data as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td class="column-min"><?=$v['id']?></td>
                    <td><a href="<?=Site::getModurl()?>/<?=$v['alias']?>"><?=$v['title']?></a></td>
                    <td class="last-column">
                        <?=Form::btnEdit(Site::getModurl().'/editfaculty/' . $v['id'])?>
                        <?=Form::btnDelete(Site::getModurl().'/delete/faculty/' . $v['id'])?>
                    </td>
                </tr>
            <?endforeach?>
        </tbody>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
</form>