<?
UAppBuilder::setH('Факультеты');

$arTitles = array(
    UForm::checkbox('check_all', 1, false, 'check-all'),
    'ID',
    'Название факультета',
    ''
);
?>

<div class="setting-panel">
    <?=UForm::btnNew('Создать новый факультет', USite::getModurl() . '/newfaculty')?>
    <?//UForm::btnNew('Создать новую специальность', USite::getModurl() . '/newspeciality')?>
</div>

<?if (empty($arResult['data'])):?>
    Список пуст
<?else:?>

    <div class="bs-callout bs-callout-warning">
        <p>
            Для создания новых специальностей необходимо перейти в раздел <b>факультета</b>
        </p>
    </div>

    <form action="" method="post" class="formaction">
        <table class="table table-hover">
            <thead>
                <tr>
                <?foreach($arTitles as $title):?>
                    <th><?=$title?></th>
                <?endforeach?>
                </tr>
            </thead>
            <?foreach($arResult['data'] as $k => $v):?>
                <tr>
                    <td><?=UForm::checkbox("i[item_{$v['id']}]", $v['id'], 'check-one')?></td>
                    <td><?=$v['id']?></td>
                    <td><a href="<?=USite::getModurl()?>/faculty/<?=$v['alias']?>"><?=$v['title']?></a></td>
                    <td class="last-column"><?=UForm::btnEdit(USite::getModurl().'/editfaculty/', $v['id'])?><?=UForm::btnDelete(USite::getModurl().'/delete/', 'faculty/'.$v['id'])?></td>
                </tr>
            <?endforeach?>
        </table>
        <?=UForm::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
    </form>
    
<?endif;?>