<?
UAppBuilder::setH($arResult['vars']['id'] ? 'Редактирование факультета' : 'Создание нового факультета');
UAppBuilder::addBreadcrumb (UAppBuilder::getH(), USite::getUrl());

$v = $arResult['data'];
?>

<? 
if ($arResult['errors'] == ERROR_ELEMENT_NOT_FOUND) {
    echo UForm::error('Факультет не найден');
    return; 
} 
?>

<?
if (!empty($arResult['errors'])) {
    echo UForm::error($arResult['errors'], true);
} 
?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Наименование факультета:<?=UForm::isRequired()?></label>
        <div class="col-lg-10">
            <?=UForm::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=UForm::button($arResult['vars']['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=UForm::input('hidden', 'id', $v['id'])?>
    <?=UForm::input('hidden', 'a', 'Y')?>
</form>