<?
use UTest\Kernel\Form;

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return; 
}

if ($this->hasErrors()) {
    echo Form::error($this->getErrors(), true);
}

$v = $data['form'];
?>

<form class="form-horizontal" method="post" action="">
    <div class="form-group">
        <label class="col-lg-2 control-label">Название специальности:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'title', $v['title'] , 'form-control', false, array('autofocus' => 'autofocus'))?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Код специальности:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::input('text', 'code', $v['code'] , 'form-control', false)?>            
        </div>
    </div>
    <div class="form-group">
        <label class="col-lg-2 control-label">Факультет:<?=Form::asterisk()?></label>
        <div class="col-lg-10">
            <?=Form::select('faculty_id', $data['faculty_list'] , $v['faculty_id'], null, 'form-control')?>            
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-lg-10">
            <?=Form::button($vars['id'] ? 'Изменить' : 'Создать', 'btn btn-default')?>            
        </div>
    </div>
    <?=Form::input('hidden', 'id', $v['id'])?>
    <?=Form::input('hidden', 'a', 'Y')?>
</form>