<?
use UTest\Kernel\Form;
use UTest\Kernel\Site;

$arTitles = array(
    Form::checkbox('check_all', 1, false, 'check-all'),
    'ID' => 'int',
    'Название специальности' => 'string',
    'Код специальности' => 'string',
    'Управление'
);

if ($this->hasErrors(ERROR_ELEMENT_NOT_FOUND)) {
    echo Form::error($this->getErrors(ERROR_ELEMENT_NOT_FOUND));
    return;
}
?>

<div class="setting-panel">
    <?=Form::btnNew('Создать новую специальность', Site::getUrl() . '/newspeciality')?>
</div>

<? if (count($data) == 0) {
    echo Form::info('Список пуст');
    return; 
} 
?>

<form action="" method="post" class="formaction">
    <table class="table table-hover table-sort">
        <thead>
            <tr>
                <?foreach($arTitles as $k => $v):
                    $title = is_string($k) ? $k : $v;
                    $dataSort = is_string($k) ? "data-sort='{$v}'" : '';
                ?>
                    <th <?=$dataSort?>><?=$title?></th>
                <?endforeach?>
            </tr>
        </thead>
        <tbody>
            <?foreach($data as $k => $v):?>
                <tr>
                    <td class="checkbox-column"><?=Form::checkbox("i[]", $v['id'], 'check-one')?></td>
                    <td class="column-min"><?=$v['id']?></td>
                    <td><?=$v['title']?></td>
                    <td><?=$v['code']?></td>
                    <td class="last-column">
                        <?=Form::btnEdit(Site::getUrl().'/editspeciality/' . $v['id'])?>
                        <?=Form::btnDelete(Site::getModurl().'/delete/speciality/' . $v['id'])?>
                    </td>
                </tr>
            <?endforeach?>
        </tbody>
    </table>
    <?=Form::button('Удалить выбранные', 'btn btn-danger delete-selected', 'del_all', 'Y', 'submit', true)?>
</form>