<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);



return array(
    'UBase' => KERNEL_PATH . '/UBase.php',
    'R' => KERNEL_PATH . '/db/rb_v4.3.2.php',
    'upload' => KERNEL_PATH . '/libs/upload/class.upload.php'
);
