<?
$debugInfo = $arResult['data'][0];
$first = true;
?>

<div class="well">
    <?foreach ($debugInfo as $k => $v):?>
        <?= ($first ? '' : '<hr/>') ?>    
        <p><strong><?=$v['name']?>:</strong></p>                
        <?
        switch ($k)
        {
            case 'call':
                echo "<div style='margin:0' class='alert alert-warning alert-mini'>{$v['value']}</div>";
                break;
            
            case 'template':
            case 'do_action':            
                echo "<ol>";
                foreach ($v['value'] as $value)
                {
                    $key = $k == 'template' ? 'template' : 'method';
                    
                    echo "<li style='margin-bottom:10px;'>";
                    echo "<span style='color:#DE5145'>{$value[$key]}</span>";
                    echo "<div style='font-size:80%;color:#999'>{$value['file']}, <span style='color:#000'>{$value['line']}</span></div>";
                    echo $key == 'method' ? "<div>{$value['args']}</div>" : '';
                    echo "</li>";
                }
                echo "</ol>";
                break;
            
            default: 
                echo $v['value'];
                break;
        }
        $first = false;
        ?>
    <?endforeach;?>
</div>